"""OpenAI-compatible Pydantic models for request/response types."""

from typing import Any, Literal

from pydantic import BaseModel, Field

# ============================================================================
# Chat Completions API Models
# ============================================================================


class ChatCompletionMessage(BaseModel):
    """A single message in a chat completion conversation."""

    role: Literal["system", "user", "assistant", "tool", "function"] = Field(
        ..., description="The role of the message author"
    )
    content: str | None = Field(default=None, description="The contents of the message")
    name: str | None = Field(default=None, description="An optional name for the participant")
    tool_calls: list[dict[str, Any]] | None = Field(default=None, description="Tool calls")
    tool_call_id: str | None = Field(
        default=None, description="Tool call that this message is responding to"
    )


class ChatCompletionRequest(BaseModel):
    """Request body for /v1/chat/completions endpoint."""

    model: str = Field(default="youtube-ask-proxy", description="ID of the model to use")
    messages: list[ChatCompletionMessage] = Field(
        ..., description="A list of messages comprising the conversation so far"
    )
    temperature: float | None = Field(
        default=1.0, ge=0.0, le=2.0, description="Sampling temperature"
    )
    top_p: float | None = Field(
        default=1.0, ge=0.0, le=1.0, description="Nucleus sampling parameter"
    )
    n: int | None = Field(default=1, ge=1, le=10, description="Number of completions to generate")
    stream: bool | None = Field(
        default=False, description="Whether to stream back partial progress"
    )
    stop: str | list[str] | None = Field(
        default=None, description="Up to 4 sequences where the API will stop generating"
    )
    max_tokens: int | None = Field(
        default=None, ge=1, description="Maximum number of tokens to generate"
    )
    presence_penalty: float | None = Field(default=0.0, ge=-2.0, le=2.0)
    frequency_penalty: float | None = Field(default=0.0, ge=-2.0, le=2.0)
    logit_bias: dict[str, float] | None = Field(default=None)
    user: str | None = Field(
        default=None, description="A unique identifier representing your end-user"
    )
    response_format: dict[str, Any] | None = Field(
        default=None, description="Response format configuration"
    )

    # YouTube-specific extensions
    video_url: str | None = Field(
        default=None,
        description="YouTube video URL or video ID. Inferred from messages if not provided.",
    )


class ChatCompletionChoice(BaseModel):
    """A single chat completion choice."""

    index: int = Field(..., description="The index of the choice in the list of choices")
    message: ChatCompletionMessage = Field(
        ..., description="A chat completion message generated by the model"
    )
    finish_reason: (
        Literal["stop", "length", "tool_calls", "content_filter", "function_call"] | None
    ) = Field(default="stop", description="The reason the model stopped generating tokens")
    logprobs: dict[str, Any] | None = Field(default=None)


class ChatCompletionResponse(BaseModel):
    """Response body for /v1/chat/completions endpoint."""

    id: str = Field(..., description="A unique identifier for the completion")
    object: Literal["chat.completion"] = Field(default="chat.completion")
    created: int = Field(
        ..., description="The Unix timestamp (in seconds) of when the completion was created"
    )
    model: str = Field(..., description="The model used for completion")
    choices: list[ChatCompletionChoice] = Field(
        ..., description="A list of chat completion choices"
    )
    usage: dict[str, int] | None = Field(
        default=None,
        description="Usage statistics for the completion request",
    )
    system_fingerprint: str | None = Field(default=None)


class ChatCompletionStreamChoice(BaseModel):
    """A single streaming chat completion chunk choice."""

    index: int = Field(...)
    delta: ChatCompletionMessage = Field(
        ..., description="A chat completion delta generated by streamed model responses"
    )
    finish_reason: (
        Literal["stop", "length", "tool_calls", "content_filter", "function_call"] | None
    ) = Field(default=None)
    logprobs: dict[str, Any] | None = Field(default=None)


class ChatCompletionStreamResponse(BaseModel):
    """Streaming chunk response for /v1/chat/completions endpoint."""

    id: str = Field(...)
    object: Literal["chat.completion.chunk"] = Field(default="chat.completion.chunk")
    created: int = Field(...)
    model: str = Field(...)
    choices: list[ChatCompletionStreamChoice] = Field(...)
    system_fingerprint: str | None = Field(default=None)


# ============================================================================
# Models API
# ============================================================================


class ModelData(BaseModel):
    """Data about a single model."""

    id: str = Field(..., description="The model identifier")
    object: Literal["model"] = Field(default="model")
    created: int = Field(default=0)
    owned_by: str = Field(default="youtube-ask-proxy")


class ModelListResponse(BaseModel):
    """Response for /v1/models endpoint."""

    object: Literal["list"] = Field(default="list")
    data: list[ModelData] = Field(..., description="List of available models")


# ============================================================================
# Error Models
# ============================================================================


class APIErrorDetail(BaseModel):
    """OpenAI-style error detail."""

    message: str = Field(...)
    type: str | None = Field(default=None)
    param: str | None = Field(default=None)
    code: str | None = Field(default=None)


class APIErrorResponse(BaseModel):
    """OpenAI-style error response wrapper."""

    error: APIErrorDetail = Field(...)
